# Generated by Django 2.0.1 on 2018-03-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.TextField(default='')),
                ('case_url', models.TextField(default='')),
                ('last_updated', models.TextField(default='')),
                ('tags', models.TextField(default='')),
                ('specific_violation', models.TextField(default='')),
                ('company_type', models.TextField(default='')),
                ('company_type_key', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('subprinciples', models.TextField(default='')),
                ('notes', models.TextField(default='')),
                ('positive_recommendations', models.TextField(default='')),
                ('data_usage', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('industries', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='FilterModel',
        ),
    ]
