# Generated by Django 2.0.1 on 2018-01-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=100)),
                ('case_url', models.CharField(max_length=100)),
                ('case_number', models.CharField(max_length=100)),
            ],
        ),
    ]
