# Generated by Django 2.0.1 on 2018-01-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0002_dataentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='company_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='company_type_key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='jurisdiction',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='last_updated',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='specific_violation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='case_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='case_number',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='case_url',
            field=models.TextField(default=''),
        ),
    ]
