# Generated by Django 2.0.1 on 2018-03-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0002_auto_20180301_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='data_usage',
            new_name='data_type',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='notes',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='dataentry',
            old_name='positive_recommendations',
            new_name='pos_rec',
        ),
    ]
