# Generated by Django 2.0.1 on 2018-01-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0003_auto_20180128_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_filter', models.CharField(choices=[('Retail', 'Retail'), ('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Mobile Application', 'Mobile Application'), ('Sports', 'Sports'), ('Hardware', 'Hardware'), ('Other', 'Other'), ('Health', 'Health'), ('Social Platform', 'Social Platform'), ('Real estate', 'Real estate'), ('Automotive', 'Automotive'), ('Consumer Reporting Agency', 'Consumer Reporting Agency'), ('Telecommunications', 'Telecommunications'), ('Financial Services', 'Financial Services')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='filtermodel',
            name='filter_options',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Mobile Application', 'Mobile Application'), ('Sports', 'Sports'), ('Hardware', 'Hardware'), ('Other', 'Other'), ('Health', 'Health'), ('Social Platform', 'Social Platform'), ('Real estate', 'Real estate'), ('Automotive', 'Automotive'), ('Consumer Reporting Agency', 'Consumer Reporting Agency'), ('Telecommunications', 'Telecommunications'), ('Financial Services', 'Financial Services')], max_length=100),
        ),
    ]
