# Generated by Django 2.0.1 on 2018-03-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0003_auto_20180301_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='note',
            new_name='notes',
        ),
    ]
