# Generated by Django 2.0.1 on 2018-02-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0004_auto_20180129_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='case_number',
        ),
        migrations.AlterField(
            model_name='keymodel',
            name='chosen_filter',
            field=models.CharField(max_length=100),
        ),
    ]
