# Generated by Django 2.0.1 on 2018-03-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0005_auto_20180301_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='company_type',
        ),
    ]
