# Generated by Django 2.0.1 on 2018-02-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0005_auto_20180201_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyModel',
        ),
    ]
