# Generated by Django 2.0.1 on 2018-02-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0006_delete_keymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterModel',
        ),
    ]
