# Generated by Django 2.0.1 on 2018-02-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0007_delete_filtermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='subprinciple',
            field=models.TextField(default=''),
        ),
    ]
