# Generated by Django 2.0.1 on 2018-03-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0007_auto_20180301_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubprincipleOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subprinciple_choice', models.CharField(choices=[('1', '1'), ('1.1.0', '1.1.0, Privacy Policy'), ('1.1.1', '1.1.1, Communication to Internal Personnel'), ('1.1.2', '1.1.2, Responsibility and Accountability for Policies'), ('1.2.1', '1.2.1, Review and Approval'), ('1.2.2', '1.2.2, Consistency of Privacy Policies and Procedures With Laws and Regulations'), ('1.2.3', '1.2.3, PI/PII Identification and Classification'), ('1.2.4', '1.2.4, Risk Assessment'), ('1.2.5', '1.2.5, Consistency of Commitments With Privacy Policies and Procedures'), ('1.2.6', '1.2.6, Infrastructure and Systems Management')], default=None, max_length=100, null=True, verbose_name='Which privacy subprinciples apply? Select all that apply.')),
            ],
        ),
        migrations.RemoveField(
            model_name='dataentry',
            name='subprinciples',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='subprinciples',
            field=models.ManyToManyField(to='display_data_app.SubprincipleOptions'),
        ),
    ]
