# Generated by Django 2.0.1 on 2018-03-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0008_auto_20180301_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='subprinciples',
            field=models.ManyToManyField(blank=True, to='display_data_app.SubprincipleOptions'),
        ),
    ]
