# Generated by Django 2.0.1 on 2018-02-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0008_auto_20180209_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('industries', models.TextField(default='')),
            ],
        ),
    ]
