# Generated by Django 2.0.1 on 2018-02-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0009_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='data_type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataentry',
            name='pos_rec',
            field=models.TextField(default=''),
        ),
    ]
