# Generated by Django 2.0.1 on 2018-03-01 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0010_auto_20180301_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='positive_recommendations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='display_data_app.Recommendations'),
        ),
    ]
