# Generated by Django 2.0.1 on 2018-03-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0012_recommendations_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='positive_recommendations',
        ),
        migrations.AddField(
            model_name='dataentry',
            name='positive_recommendations',
            field=models.ManyToManyField(to='display_data_app.Recommendations'),
        ),
    ]
