# Generated by Django 2.0.1 on 2018-03-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0013_auto_20180301_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='text',
            field=models.TextField(default='', null=True),
        ),
    ]
