# Generated by Django 2.0.1 on 2018-03-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0014_auto_20180301_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='positive_recommendations',
            field=models.ManyToManyField(blank=True, to='display_data_app.Recommendations'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
