# Generated by Django 2.0.1 on 2018-03-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0015_auto_20180301_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='positive_recommendations',
            field=models.ManyToManyField(blank=True, null=True, to='display_data_app.Recommendations'),
        ),
    ]
