# Generated by Django 2.0.1 on 2018-03-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0016_auto_20180301_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='text',
            field=models.TextField(blank=True, default='', max_length=10, null=True),
        ),
    ]
