# Generated by Django 2.0.1 on 2018-03-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0017_auto_20180301_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
