# Generated by Django 2.0.1 on 2018-03-04 13:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('display_data_app', '0018_auto_20180304_1317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendations',
            new_name='Recommendation',
        ),
    ]
