# Generated by Django 2.0.1 on 2018-03-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('display_data_app', '0019_auto_20180304_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='positive_recommendations',
            field=models.ManyToManyField(blank=True, to='display_data_app.Recommendation'),
        ),
    ]
