# Generated by Django 2.0.1 on 2018-03-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0020_auto_20180304_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='notes',
        ),
    ]
