# Generated by Django 2.0.1 on 2018-03-21 10:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0021_remove_dataentry_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataentry',
            name='subprinciples',
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='data_usage',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Collection', 'Collection'), ('Access', 'Access'), ('Use', 'Use'), ('Disclosure', 'Disclosure')], help_text="<div style='float:right;font-size:12px;color:red'> HELP TEXT DISPLAYED HERE</div>", max_length=100, null=True),
        ),
    ]
