# Generated by Django 2.0.1 on 2018-03-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0022_auto_20180321_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='priority_number',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
