# Generated by Django 2.0.1 on 2018-03-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0023_recommendation_priority_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='subprinciples',
            field=models.TextField(default=''),
        ),
    ]
