# Generated by Django 2.0.1 on 2018-03-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0025_auto_20180322_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='subprinciple',
            field=models.TextField(default=''),
        ),
    ]
