# Generated by Django 2.0.1 on 2018-04-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_data_app', '0028_recommendation_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
